mod rewrite_gc_type_to_id_type;
mod rewrite_ref_type_to_id_type;

pub use rewrite_gc_type_to_id_type::rewrite_gc_type_to_id_type_rule;
pub use rewrite_ref_type_to_id_type::rewrite_ref_type_to_id_type_rule;
