plugins:
  rustfmt:
    path: ../../tree-sitter-lint-plugin-rustfmt
  rust-known-imports:
    path: ../../tree-sitter-lint-plugin-rust-known-imports
rules:
  # rewrite-gc-type-to-id-type:
  #   level: error
  rustfmt/rustfmt:
    level: error
  rust-known-imports/known-imports:
    level: error
    options:
      known_imports:
        AllArenas:
          module: crate
          kind: type
        EmitNode:
          module: crate
          kind: type
        Node:
          module: crate
          kind: type
        NodeArray:
          module: crate
          kind: type
        ReadonlyTextRangeConcrete:
          module: crate
          kind: type
        Symbol:
          module: crate
          kind: type
        SymbolTable:
          module: crate
          kind: type
        Type:
          module: crate
          kind: type
        set_text_range_node:
          module: crate
          kind: function
        _d:
          module: crate
          kind: function
        Id:
          module: id_arena
          kind: type
        Arena:
          module: id_arena
          kind: type
        RefCell:
          module: std::cell
          kind: type
        Cell:
          module: std::cell
          kind: type
tree-sitter-lint-dependency:
  path: ../../tree-sitter-lint
